Repository ocornut/imgui, pull requests merged in 2019-05, with the labels that each got.

#2527 Examples: Add GLFW+Metal example
  examples/example_glfw_metal/Makefile
  examples/example_glfw_metal/main.mm
Labels: backend/binding

#2547 Platform Binding for GLFW updated with the release of GLFW 3.3
  examples/imgui_impl_glfw.cpp
Labels: backend/binding, viewport

#2546 Add native mac copy/paste support to imgui.cpp
  examples/example_apple_opengl2/example_apple_opengl2.xcodeproj/project.pbxproj
  examples/imgui_impl_osx.mm
  imgui.cpp
Labels: backend/binding, osx/ios

#2584 Fix error in OpenGL3 implementation
  examples/imgui_impl_opengl3.cpp
Labels: backend/binding

#2585 Added mouse cursor support for OSX examples
  examples/imgui_impl_osx.mm
Labels: backend/binding, osx/ios
