Repository ocornut/imgui, pull requests merged in 2023-07, with the labels that each got.

#6568 Fix outdated link in freetype docs
  misc/freetype/README.md
Labels: doc

#6573 Changing SDL_WINDOW_SKIP_TASKBAR to SDL_WINDOW_UTILITY for SDL3
  backends/imgui_impl_sdl3.cpp
Labels: backends, multi-viewports

#6658 imgui_stdlib: Fix warning
  misc/cpp/imgui_stdlib.cpp
Labels: building

#6656 Mark alternative ImColor constructors as constexpr
  imgui.h
Labels: cplusplus
