Repository ocornut/imgui, pull requests merged in 2024-05, with the labels that each got.

#7585 Fix compiling when using GDK
  imgui.cpp
Labels: backends

#7599 Fix typos in comments
  imgui.cpp
  imgui_tables.cpp
Labels: doc

#7614 MSVC: Initialize last_pixel_unpack_buffer in opengl3 backend
  backends/imgui_impl_opengl3.cpp
Labels: backends, opengl, building

#7620 Fix off-by-one typo in `IsMouseDragging` and `GetMouseDragDelta`'s documentation
  imgui.h
Labels: doc

#7641 Fixed Makefiles for sdl3 examples
  examples/example_sdl3_opengl3/Makefile
  examples/example_sdl3_sdlrenderer3/Makefile
Labels: backends, building
